# Setup
title: Howard's Blog
tagline: Random Thoughts for Everything
paginate:     1
locale:       "en"

# About/contact
author:
  name:       howard0su@gmail.com
  url:        https://howard0su.github.io 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
