# Setup
title: Howard's Blog
tagline: Random Thoughts for Everything
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Howard Su
  url:        mailto:howard0su@gmail.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
